### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by rsanchez** [markhuot/craftql#11]
Is pagination built-in? If so, can you show an example? If not, consider this a feature request 😄

**Comment by markhuot** [comment]
It's not built in. You can use `{ entries(limit:10, offset:50) {...} }` to get pages of data though. Currently there's no way to get `{% paginate…` style data…

Aside: I've considered moving to a GraphQL style `after:` param but it's a lot of complexity to implement on top of Craft so it's probably much further down the road. Plus I'm hoping Craft adds it natively.

Further aside: I'm still thinking of how to call `{ entries(limit:10) {...} }` and get back the `.count`/total number of rows… I can't shove it in the response because the `entries` field returns an array. This is where Relay style "connection" objects would help.

**Comment by rsanchez** [comment]
Ideally, you'd get back similar variables to what you'd get from the `{% paginate %}` tag, perhaps in a `meta` key of the response, alongside the `entries` key.

There's a method for getting pagination data from an `ElementQuery`: [`\craft\helpers\Template::paginateCriteria`](https://github.com/craftcms/cms/blob/687f1fb3678b964be67e40535b503c2e47a48200/src/helpers/Template.php#L84-L137), which returns an instance of [`\craft\web\twig\variables\Paginate`](https://github.com/craftcms/cms/blob/develop/src/web/twig/variables/Paginate.php).

Maybe a `paginate: true` parameter? Or maybe a different method like `{ paginatedEntries() }`?

**Comment by markhuot** [comment]
Yea… `paginatedEntries` feels the most "Craft like" to me, but it's a slippery slope because I want to support Relay eventually and then I'll need "Connection" types anyway, which would do the same thing as `paginatedEnteies`. I'll mess around with this and see what feels the best. I have some pagination stuff on a local branch, let me see where I left that…

**Comment by StevenLangbroek** [comment]
In general GraphQL implementations I've seen so far prefer cursor-based pagination... Not sure how it would map to Craft's domain, but here's what the docs say: http://graphql.org/learn/pagination/

**Comment by markhuot** [comment]
Yea, I've thought about that as well. It complicates things considerably though. Imagine these few queries,

```graphql
{
  entries {
    id
  }
}
```

vs.

```graphql
{
  entries {
    edges {
      node {
        id
      }
    }
  }
}
```

These are obviously not apples to apples comparisons though as the first one has _no_ way of getting page information… The later "connection" based approach could be extended to return a host of data with the result set,

```graphql
{
  entries {
    totalCount
    edges {
      node {
        id
      }
      cursor
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
}
```

From your perspectives would it be helpful to offer multiple root fields so you could choose the simple or complex approach? Or would you just force everyone through the more "standard" connection based approach?

**Comment by StevenLangbroek** [comment]
Well we've been implementing GraphQL at my current dayjob for well over a year now, so I'm pretty familiar with how this works, so for me, I'd prefer the "standard" edges / nodes implementation. If there's ever a time to make this switch it's before this plugin gains the traction I'm expecting it will...

**Comment by markhuot** [comment]
It's a fair point. But one of the draws of Craft, IMO, is the low barrier to entry. I don't want to drop a bunch of complexity on top of system as simple to get started with as Craft. Right now I'm exploring,

1. A config option that allows you to toggle the entire schema into connections or "simple" mode.
2. Separate fields on the root query for things like `entries(section:news)` and `entriesConnection(section:news)`

Would either of those help here?

**Comment by StevenLangbroek** [comment]
Personally I'd prefer the config option, but I can imagine relatively simple builds that have 1 or 2 complex cases, would be a shame to have to choose the complex output just for that... So separate fields on root sounds like a more solid approach...

**Comment by markhuot** [comment]
Agreed, and less config is always a win, in my book.

**Comment by StevenLangbroek** [comment]
Documentation wise this has a good narrative to it as well.

**Comment by markhuot** [comment]
Okay, I took an early pass at this on `dev-master`. It adds a new top level field to the `query` called `entriesConnection`. All existing functionality is still present in the `entries` field.

The new `entriesConnection` field _should_ behave like a traditional GraphQL connection with all the associated `edges` and `node` types. So,

```graphql
{
  entriesConnection(limit: 10, offset: 50) {
    totalCount
    pageInfo {
      hasPreviousPage
      hasNextPage
    }
    edges {
      node {
        id
        title
        ...on Stories {
          fooConnection {  # where this is an Entries custom field
            edges {
              node {
                id
              }
            }
          }
        }
      }
    }
  }
}
```

This work does not involve cursors yet, because, well, they're complex and Craft doesn't support them natively so I'm sort of going to have to hack them on top of the native `offset` and `limit` stuff…

![screen shot 2017-09-06 at 4 26 09 pm](https://user-images.githubusercontent.com/48975/30133121-a4923498-9320-11e7-9192-d22d3c6821c3.png)

@rsanchez, regarding your original question. You can now get `{% paginate…` style data from the connections. E.g.,

```graphql
{
  entriesConnection {
    totalCount
    pageInfo {
      hasPreviousPage
      hasNextPage
      currentPage
      totalPages
      first
      last
    }
    edges {
      node {
        id
      }
    }
  }
}
```

**Comment by markhuot** [comment]
I've been thinking about this for a while and I'm pretty happy with the outcome. I'm going to close this issue now. One note: I added an `entries` field to the `entriesConnection` so you can more easily get total results without dealing with all the `edges`/`nodes` stuff. E.g.,

```graphql
{
  entriesConnection {
    totalCount
    entries {
      ...on Posts {
        title
        body
      }
    }
  }
}
```
