### ISSUE TITLE
Adding fields to an existing interface/field type

### ISSUE THREAD

**Issue by timkelty** [markhuot/craftql#122]
The Third-party integration docs seemed focused on third-party _fields_, but in this case I merely want to add to an existing interface (`markhuot\CraftQL\Types\VolumeInterface`).

Here's where I'm at (which doesn't work):

```php
        Event::on(\craft\fields\Assets::class, 'craftQlGetFieldSchema', function (\markhuot\CraftQL\Events\GetFieldSchema $event) {
            $field = $event->sender;

            $event->schema->addStringField('path')
                ->resolve(function ($root, $args) {
                    return rtrim($root->volume->subfolder, '/') . '/' . $root->path;
                });

            $focalPoint = $event->schema->createObjectType('AssetFocalPoint');
            $focalPoint->addFloatField('x');
            $focalPoint->addFloatField('y');
            $focalPoint->addFloatField('left');
            $focalPoint->addFloatField('top');
            $focalPoint->addFloatField('right');
            $focalPoint->addFloatField('bottom');
            $focalPoint->addStringField('coords');

            $event->schema->addField('focalPoint')
            ->type($focalPoint)
            ->resolve(function ($root, $args) {
                $focalPoint = $root->getFocalPoint();
                $values = array_map('floatval', array_merge($focalPoint, [
                    'left' => $focalPoint['x'] * $root->width - 1,
                    'top' => $focalPoint['y'] * $root->height - 1,
                    'right' => $focalPoint['x'] * $root->width + 1,
                    'bottom' => $focalPoint['y'] * $root->height+ 1,
                ]));

                $values['coords'] = implode('', [
                    $values['left'],
                    'x',
                    $values['top'],
                    ':',
                    $values['right'],
                    'x',
                    $values['bottom'],
                ]);

                return $values;
            });
        });
```

Do we need a separate hook for changing core types, or is there another way?

**Comment by markhuot** [comment]
Ah, I see, you're correct: the current event is meant for adding new fields to the schema. What you have above is probably adding a `path` field on to all of the EntryTypes that have an assets field. Check the documentation explorer and see if your new custom `coords` shows up under the content type (next to title, slug, postDate, etc…).

You could use this to add a _new_ field next to the entry type. So, if your field in Craft is named `heroImage` then you'll get the default functionality in CraftQL of a similarly name `heroImage` GraphQL field. You could use the above to add a new field called `heroImagePlus` (or something) that would have your custom fields. Basically, I think the above _is_ working but it's one level higher than you need/expect.

Long term I think I like the idea of adding _additional_ fields instead of modifying the default ones. Mostly because if you have two plugins modifying a field you could end up in a world of hurt with the conflicts that arise. Maybe I offer the ability to _disable_ the default field types and allow custom plugins to provide their own implementations that way…

**Comment by timkelty** [comment]
> Check the documentation explorer and see if your new custom coords shows up under the content type (next to title, slug, postDate, etc…).

Indeed, thats what was happening.
