### ISSUE TITLE
CLI server in production?

### ISSUE THREAD

**Issue by timkelty** [markhuot/craftql#133]
From README:

> Caution: this can also create unintended side effects since Craft is not natively built to run this way. Do not use this in production it could lead to memory leaks, server fires, and IT pager notifications :).

Wondering if you could elaborate on this a bit…especially the "Craft is not natively built to run this way" bit…it seems like Craft/Yii console commands are designed specifically for this type of use.

Obviously there other considerations (daemonizing process, etc), but some devs are already using Craft in this way (e.g. running a `craft queue/listen` process).

**Comment by narration-sd** [comment]
Hey, Tim -- I had been a little curious myself.

I guess I should say in preview that Live Vue essentially provides this server function itself, not only in preview, and in a way that has spa startup performance advantages over directly connecting. I'll explain this in the doc,  which is the task right now.

I'll need to hear from guys like yourself about any issues with this, which is why I hint betas. 

I was also quite interested in base performance of CraftQL after observing during development, but on Monday made some admittedly simple tests, with xdebug disabled on the server, and key point for CraftQL, Craft devMode set to off. 

In these simple tests it looked like CraftQL is right in the same ballpark as element-api -- maybe  20% slower is all, which would not be noticed.

devMode on, things change, as CraftQL then does a lot of assert operation -- turning on blackfire shows it spends 80% of its time there in fact, all above normal query operation, but this is good also for confidence in scripts, as long as you know it's happening.

**Comment by markhuot** [comment]
The biggest concern with the CLI server is that Craft sessions aren't typically meant for long running processes. So, if User A logs in at 9am and then User B accesses the site immediately after, at 9:01am there's a chance that the session from User A could bleed in to User B's session. I've done what I can to prevent this, but it has not been thoroughly tested, hence the warning.

If anyone _does_ decide to do this in production, let me know and I'd be happy to help out with any issues.

**Comment by narration-sd** [comment]
Mark, thanks for clarifying.. I think there are a number of other things involved in a long-running service, but due to people wanting to run node, many of these  are clarified at least for Digital Ocean, a quick search discloses, and mainly that they are friendly to this. It's not just running Craft Cli in the background, of course.

I'm interested but take your word about possible session crossover, guessing this has to do with session tokens as much as anything.

Another facet I'm thinking about would be the need for the Vue/etc. spa app to become clear itself on just what Craft Site is intended to be in play for a given query. Like most things I've had to deal with, this isn't transparently apparent out on the client.

The server-like facet of Live Vue for not-in-preview api or gql requests can get around this problem, and may be adequate on its own for many. 

I forgot to mention I'm getting around 120ms turnaround for CraftQL requests in this mode, which operates automatically. That's on a fast laptop, running Craft etc. in a Vagrant VM, and Chrome on Windows 10 itself. Again, not any full-bore test, but encouraging.

**Comment by narration-sd** [comment]
> The way we have it set up, we're basically requiring the site parameter, as all of our API requests come from the same domain.

Ah, interesting -- and this kind of thing is just why I want a beta, to those who really exploit  things.

I have already a hard request protocol/domain url capability possible in the js-side config, for that part. Which I'm supposing is because you really do or may feel you want to run a separated gql server.

I think everything will work out automatically for actual Live Preview with Live Vue, because the element you'll be editing will be of the current Site, and that's the data that api or gql will transparently see, will pass down to the automatic bypass my Connect objects provide for your spa app.
 
At first glance, it may be that the live site gql calls also are already provided for. I've centered on having gql scripts on the server, called by name, but there's also the ability to pass them in POST, which is how I presume you're doing in this case. It's pretty untested, but that can be a highlight on a beta, and should be straightforward.

Still thinking....

**Comment by timkelty** [comment]
I have already a hard request protocol/domain url capability possible in the js-side config, for that part. Which I'm supposing is because you really do or may feel you want to run a separated gql server.

For the current project I'm working on, all the siteUrls for my Craft sites point to non-craft server (e.g. site.co.uk, site.de – while the Craft CP, and all API requests are served from `cms.site.com`.

**Comment by narration-sd** [comment]
Ok, last question for the day, if it may lead to others later:

 - How many query scripts would you say you have on the project?  

And where this could lead is thoughts about whether a Craft config script is adequate to hold copies of them, or if we need to be thinking of something further...

**Comment by timkelty** [comment]
Clive,
You mean just like how many unique gql queries am I using?

**Comment by narration-sd** [comment]
...just caught me.  Yup....

**Comment by timkelty** [comment]
@narration-sd,
In this current build, not very many, actually. Maybe 5 or 6 unique ones?

It looks as though the way this one is going, instead there are just really massive "page" queries that cover a ton of types.

Then again, this build isn't terribly "app"-y and is really just more of a standard informational/brochure site. The frontend devs wanted to go headless because they're 100% React devs and are doing all sorts of fancy animations and transitions :)

**Comment by narration-sd** [comment]
Great --

Sounds very workable, even with tens. And I'm away, but the I have siteId
already something they can pass, or did; anyway, easy to provide.

My thinking is, as they hook up developed parts, they'd just move their
queries into Craft-side config, and call for them by name

Makes for cleaner components, also.

I knew react would be coming, and there will be things to work out compared
to Vue's router abilities, but the rest is straight es6, so should work out.

Thanks, and more soon.

**Comment by narration-sd** [comment]
Tim, just wanted to add for a Friday that I've removed all vestiges of Vue-router from the client-side objects, so this should make the way clear for React.

I want to get Live Vue-only discussion off Mark's page now, as know he'd appreciate, so will be setting up a git place to discuss Live Vue. Crossovers of course still here.

I'm still monkeying around with repository choices, and wonder if you'd have any problem with having BitBucket be where you'd point your Composer etc. while this is still private? 

Any private would involve a login name to be entered in a git tool for access.

A good weekend to you there. I'm getting away from code now, to pull together the notes into documentation, and should have  enough for beginning to use this thing by sometime next week.

**Comment by markhuot** [comment]
I'm going to close this because I think the original question has been answered. Feel free to re-open if anything CLI-server related comes up.
