### ISSUE TITLE
Error: FieldNameEnum values must be an array with value names as keys.

### ISSUE THREAD

**Issue by lukepearce** [markhuot/craftql#161]
I'm updating a Craft 2 site to Craft 3 and have installed CraftQL through composer but when I go to GraphiQL view I see the following error before making a query:

```
{
  "error": "MerchantDeliveryDaysEnum values must be an array with value names as keys."
}
```

The field MerchantDeliveryDays is a Checkbox field with the following values:

![image](https://user-images.githubusercontent.com/1732601/46037446-67ca2400-c108-11e8-8dec-12e9aba70db2.png)

**Comment by markhuot** [comment]
This is, unfortunately, a discrepancy in the GraphQL and Craft specs/implementations. Craft allows _anything_ in the Value of an Enum but GraphQL wants a string. E.g., `setDeliveryDays:[SUN, MON]` would be ideal for GraphQL.

You're not the first person to come across this so I'd love to help. Are you able to adjust the Value column to be strings such as `MON`, `TUE`, `WED`, etc…?

**Comment by lukepearce** [comment]
Thanks Mark. I changed the values to strings and it no longer errors. How does it handle single numerical values? Does GraphQL convert them to strings or is it a case of never using numerical values in Craft if you want to be able to use GraphQL to retrieve them?

**Comment by markhuot** [comment]
Yea, it's tricky. To use the canonical GraphQL example:

If you have the Star Wars API and you have a channel called "People" with a drop-down that stores "Species" you may have labels for "Human," "Droid," and "Wookiee". In GraphQL you would usually represent that as an Enum that only has three options, HUMAN, DROID, and WOOKIE. GraphQL usually represents the enum value as uppercase. You would then use that in a query like this,

```GraphQL
{
  allPeople(species:DROID) {
    name
  }
}
```

Notice in the above how `DROID` isn't in quotes. It's not a "string" but rather a keyword. The nice thing about GraphQL's strong type system is that species can _only_ be HUMAN, DROID, or WOOKIE and the query analyzer can type check that on input without "parsing strings."

Unfortunately, you can't have a keyword that is a number because then GraphQL wouldn't be able to determine if it's a keyword or a number (for the type system).

So, to answer your original question,

> Does GraphQL convert them to strings or is it a case of never using numerical values in Craft if you want to be able to use GraphQL to retrieve them?

If your CMS' only purpose is to be a back-end for GraphQL I would recommend not using numeric values for your drop-downs and checkboxes. However, if you're interacting with twig or you have an existing site that your adding GraphQL to then things are a bit more complex. If you can move away from numeric values that would be best. If you can't then I'm looking at adding some sort of "translation" layer that would make Craft drop-down values safe for GraphQL but I don't have a timeline on that just yet.

I'm going to close this because you said you changed the values to strings and things are working. If that's not the case or you want to chat about it further feel free to re-open the thread.
