### ISSUE TITLE
local dev `"error": "NestedLevelEnum values must be an array with value names as keys."`

### ISSUE THREAD

**Issue by hendrikeng** [markhuot/craftql#171]
I am getting: 
`"error": "NestedLevelEnum values must be an array with value names as keys."` in a local dev environment  (PHP 7.2, Laravel Valet, MariaDB) in the GraphiQl interface. 

tested with different queries and the { helloWorld } query

What am i missing? 

Thanks a lot

**Comment by markhuot** [comment]
Unfortunately this is due to how Craft and GraphQL treat drop-down content differently. My guess is you have a field with the handle of `nestedLevel` and in that you have the value of that field set to `1`, `2`, `3`, `4`, etc… (or something like that). GraphQL needs those values to be strings.

This is a duplicate of 
https://github.com/markhuot/craftql/issues/156#issuecomment-422057033 which includes a "fix" in that the error messaging is more explicit. The new error message is on `master` if you're not already testing that.

Moving forward, I'm still trying to figure out a way to "automatically" convert those values to something GraphQL can understand but I haven't figured out a clean way to do that _just_ yet.

**Comment by hendrikeng** [comment]
Thanks a lot @markhuot, it does work changing the value to a string 👍
