### ISSUE TITLE
Complex plugins?

### ISSUE THREAD

**Issue by StevenLangbroek** [markhuot/craftql#18]
I'm eyeing [engram-design/Comments](https://github.com/engram-design/Comments) for comments on my site, and was wondering what integration for something more complex like this would look like?

**Comment by markhuot** [comment]
Is it available for Craft 3 yet? I’d be happy to roll it in, but didn’t see a composer package available.

**Comment by StevenLangbroek** [comment]
Hmm... doesn't seem like it. There used to be a composer.json (if you search for "composer" 4 commits show up). I suppose I could try to hand-roll it... I have absolutely no idea how most people do this in the Craft community...

**Comment by markhuot** [comment]
Unfortunately the 2.0 to 3.0 is a major adjustment for Craft and plugins will need to be updated to support 3.0. The last commit was 8 days ago so it appears the project is still active. Your best bet is probably to open an issue over on https://github.com/engram-design/Comments and ask about Craft 3. If it turns out that Craft 3 is in the works I'd be happy to help get it working with CraftQL.

Note: the existing Craft QL logic will support this plugin without issue. The plugin will just need to define the Craft QL schema (otherwise I can patch it in to this repo, if necessary).

**Comment by StevenLangbroek** [comment]
Would it work with the existing permission model too?

**Comment by StevenLangbroek** [comment]
(Opened issue btw: engram-design/Comments#77)

**Comment by markhuot** [comment]
Sort of. There won't be a permission for "comments" out of the box, so anyone with access to `entries` would have access to the comments on that entry. I can look at allowing plugins the ability to define their own permission scopes… but that's really something Craft should do so I'll need to think on it.

Overall though, this should definitely be doable, in some state, assuming the plugin is updated for Craft 3.

**Comment by markhuot** [comment]
I'm going to close this for now. Long story short: this is definitely possible. Once I get a 1.0.0 release of CraftQL out the door I'll look to move some of my customizations out of CraftQL and in to the actual third-party field plugins. You can see an example of these complex plugins with my implementation of the [Newism Gender Field](https://github.com/newism/craft3-fields): [src/Fields/NSMGenderBehavior.php](https://github.com/markhuot/craftql/blob/master/src/Fields/NSMGenderBehavior.php)
