### ISSUE TITLE
CORS Error persists when config allowedOrigin is set to '*'

### ISSUE THREAD

**Issue by bryanjhickey** [markhuot/craftql#256]
I am have the same issue:

> Access to XMLHttpRequest at 'https://api.galleries.test/api' from origin 'https://galleries.test' has been blocked by CORS policy: Request header field x-requested-with is not allowed by Access-Control-Allow-Headers in preflight response.

I get a successful api response with `curl` passing the `--insecure` flag but get a CORS warning when attempting to access from the site

I have also tried running the site at `http://localhost:8080` 

I have set my `craftql.php` to
```
<?php

return [
    'allowedOrigins' => [
        '*', // or '*', as Tim mentions
    ]
];
```

I also tried specifying the site URL (and port for localhost) but same results

I wondered if it might be an issue with the security cert and Laravel Valet so switched to 'http://' but still received the same CORS warning.

**Comment by bryanjhickey** [comment]
Is there a way to test that `craftql.php` configs are being implemented?

**Comment by bryanjhickey** [comment]
Persisting with this issue.

POST seems to work fine ....

```
const result = await axios({
        url: endPoint,
        method: 'post',
        headers: {
          Authorization: `Bearer ${token}`
        },
        data: {
          query: query
        }
      })
```

But GET not so much ...

```
const result = await axios({
        url: endPoint,
        method: 'get',
        headers: {
          Authorization: `Bearer ${token}`
        },
        data: {
          query: query
        }
      })
```

> Access to XMLHttpRequest at 'https://api.content.test/api' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

`craftql.php` is still as shown above with `allowedOrigins' => [ '*' ]`

**Comment by narration-sd** [comment]
Fellows, I haven’t spare moments to look back into this (truly, doing high wire acts to get two products out the door), but if it hasn’t changed recently, CraftQL doesn’t deal in gets. Only posts.

I suspect this is what you’re actually running into, that its not even getting to the check on origins allowance before rejecting.

There are many questions about gets apropos; you’d have to be escaping like mad on them to even have the query pass through, and soon anyway would run into the 256 char total limit for those, no? 

And then there’s the security aspect, one would think.

Go Post, I feel, would be the advice.  This is no longer that old Reactish world, and your use of Axios gives you great tools to do this well.

I’ve been using  posts for a long time on CraftQL, and allowedOrigins works fine there; no standing on head with port numbers etc. required. With React, with Vue, with packages on top of those. Problems mostly limited to results of calling the staging server instead of dev with a newer schema, as a choice headscratching example… 

Mark's stuff most generally works, so good fortune.

**Comment by bryanjhickey** [comment]
Thanks for the explanations
