### ISSUE TITLE
Returning an array of arrays

### ISSUE THREAD

**Issue by khalwat** [markhuot/craftql#276]
Thanks to @markhuot for the help, we've added CraftQL support to SEOmatic: https://github.com/nystudio107/craft-seomatic/blob/v3/src/listeners/GetCraftQLSchema.php

But in addition to returning pre-rendered metadata, SEOmatic can return everything as an array, and people people want that option: https://github.com/nystudio107/craft-seomatic/issues/401

My question is... how would I return an array of arrays? Being fairly strongly typed, it seems like GraphQL will want to know about all of the sub-fields that are returned. For example, we might be returning something that looks like this:

```json
    "MetaTagContainer": {
        "generator": {
            "content": "SEOmatic",
            "name": "generator"
        },
        "referrer": {
            "content": "no-referrer-when-downgrade",
            "name": "referrer"
        },
        "robots": {
            "content": "all",
            "name": "robots"
        }
    },
```

c.f.: https://github.com/nystudio107/craft-seomatic#meta-container-api-endpoints

If I do this:

```php
        // Add in the CraftQL fields
        foreach (self::CRAFT_QL_FIELDS as $fieldHandle => $containerType) {
            $seomaticField
                ->addStringField($fieldHandle)
                ->lists(true)
                ->resolve(function (array $data) use ($containerType) {
                    // $root contains the data returned by the field below
                    $result = ContainerHelper::getContainerArrays(
                        [$containerType],
                        $data['uri'],
                        $data['siteId'],
                        true
                    );

                    return $result[$containerType];
                });
        }
```

It complains that:

```json
{
  "error": "String cannot represent non scalar value: associative array(1) with first key: \"generator\""
}
```

Which makes sense to me... but since this can be an arbitrarily nested JSON structure, how could this be represented in GraphQL?

The example above is only 3 levels deep, but it can be arbitrarily nested depending on the data structure.

**Comment by markhuot** [comment]
This is complex to do in GraphQL. Not impossible, but it's going to require quite a few types. For example, given your above response, you'd need a `metaTagContainer` field which returns a `MetaTagContainer` object which has a `generator` field which could return a `MetaTag` object which has `content` and `name` string fields?

Can you give me an example of the "nesting" that you're referring to?

**Comment by khalwat** [comment]
So... this is where it gets sticky but the JSON-LD container, for instance... it returns schema.org JSON-LD arrays, which can be nested arbitrarily deep. Any schema.org type can contain another schema.org type, with no cap on the number of levels deep that this is.

**Comment by markhuot** [comment]
Gotcha, so then you've have to map _every_ schema.org Type to a GraphQL "type" in order to support that level of nesting, which is why things like this exist over in the Node ecosystem, https://github.com/cape-io/graphql-schema-org.

Some wacky ways to do this:

1. when `asArray:` is passed return a JSON string instead of the HTML string. It'd then be up to the consumer to deal with decoding it. This is gross and misses the point of GraphQL, but is probably the easiest path forward.
2. come up with some abstract type that allows nesting. Something like `JSONLDObject` that contains `typeName`, `key, `value`, and `children` fields. Children could contain more `children` fields and so on an so forth. You're basically creating a bunch of value objects to store JSON-LD. This would be a pain to parse on the consuming side but more straightforward to implement on the server side.

**Comment by khalwat** [comment]
Yeah I'd thought of #1 @markhuot and thought it was gross but probably okay for this use-case. Thanks!
