### ISSUE TITLE
Error: Can't query field entries on type Query – but it actually works

### ISSUE THREAD

**Issue by Jones-S** [markhuot/craftql#313]
I am using a query like:
```
query Page($slug: String!) {
  entries(section:[pages], slug: $slug) {
    slug
    title
    
  }
}
```

Within graphiql it gives me this error

<img width="408" alt="image" src="https://user-images.githubusercontent.com/7059580/64034027-1a430c00-cb4e-11e9-8c9b-b99fc0b22df3.png">

But when I run the command I get what I wanted. So it actually works...
Does anyone know if the error is wrong or if my query indeed is wrong?

Thank you

Cheers

**Comment by narration-sd** [comment]
Look up 'inline fragments' on Types, Jonas.

How you get any but the most primary Element fields.

Grüss

**Comment by Jones-S** [comment]
Thank you for the quick response. I'll check it out.

**Comment by narration-sd** [comment]
You need them any time the fields are not part of the primary target, which in Craft's case is Element.

You are presumably querying on an Entry.  Then any fields you add as properties of its Section,, your fields defined for it, will only be present on the compound type GraphQL generates. 

That's why there's emphasis on the 'Documentation' or 'Schema' abilities in Graphiql -- so you can look these types up, as the Craft Entry Type of interest often also forms part of the compound name.

In CraftQL syntax, the first entry type is [often?] merged with the base name, so yes, as you suggest, 

```
    ... on Droid {
        body    # body is field of your Droid Entry, not of Element...
        image {
             title
             url
        }
        primaryFunction  # etc.
    }
```

In the new Craft GraphQL syntax, it's further spelled out, so something like this:
```
    ... on Droid_droid_Entry {
        body
        image {
             title
             url
        }
        primaryFunction  # etc.
    }
```

Gruezi, properly this time

**Comment by Jones-S** [comment]
Grüezi is rather used as a greeting :).

Thanks for elaborating, I still don't fully understand. I will try to read some stuff about 'Documentation' or 'Schema' abilities in Graphiql.

But also today, the same query is not warning me at all, and everything looks fine.
Maybe it was a bug?...

**Comment by narration-sd** [comment]
I can tell you what the situation looks like...

- On your first post, I was in a hurry, having only a moment, and didn't notice that the error was actually concerning 'entries'
- that it does so, would point to a permissions problem actually, since `entries` is a normal term for Craft. You are not permitted at the moment of this query to access entries; therefore it's an unknown name to CraftQL. That's the way the security operates, so there is no direct statement of permissions being involved possible.
- why would you have differing permissions the next day? It depends on what permissions GraphiQL was started with. 
  - I believe in CraftQL, it has all permission automatically when you start it from the left-hand menu on the CP screen.
  - If you instead start it from the Settings > CraftQL screen where you create tokens to represent permissions, it has the permission, as it notes, for testing a particular token. 
  - Thus if you hadn't permitted entries for the token you had been working with, on the follow-up screen linked to the right of its listing, GraphiQL accessed this way would act as though `entries` didn't exist.
  - The result would be what your error looks like. QED, as someone in English stories liked to mention. I hope.
- what does the dissertation on inline fragments mean? 
  - it's your other main way to go wrong, though the error would have been (listed on query results) that a `Field` wasn't known.
  - for `slug` and `title`, those I believe are both properties of Entries in general; thus in your first post should have worked, and presumably do now
  - but when you asked again, you noted a field `primaryFunction`, which is surely not a base Entry field. Thus it must be a  field of a particular Section's particular `entryType`, so that it requires a specific inline fragment naming that combination, before it can be seen by GraphQL. So I explained.
- You need to think in GraphQL primarily of permissions and Types, for success. Types you will note as the namings of elements, labels for their identity, properties, and positionings in the Schema. This is very orderly, so should appeal in a certain land, I think from a very interesting life there.
- Without building skills for it, Graphiql will help you a lot on most query matters like these. If you type in (or retype on a pasted query) some beginning on the element you want, the UX here will propose a list of known elements which could fit your spelling so far, and would be appropriate in the location. The information it uses is in the Schema, and so can also be looked up on screen. I think the type-and-see method is usually more efficient.
- bug: I don't think so this time. CraftQL is generally pretty sound at this level of working with it.

Ok, and thanks for reminding me where speech also places `Gruezi`, so I should have known for notes also - it was a late night instant. Mainly I was intending to be polite without the Hochdeutsch, which I could also know better. My time was very busy, full of Germans who wanted to polish their English on the demanding and largely non-technical matters we dealt with across many cultures constantly, thus with no chance to do formal language study. I like to keep up a bit with what I could do reasonably, read newspapers, and so the FAZ, Süddeutsch Zeitung, and Basler posts are in my in-tray...

**Comment by Jones-S** [comment]
OK wow. What a long and complete answer. Thank you very much. I am not sure what could have caused the error. Maybe a thing with the token settings, but this would not explain why I got a return for my query. If it reappears I try to go through each of your points. Thank you.

**Comment by Gurpreet5028** [comment]
@narration-sd  thanks man beena huge help, right on the time i needed , appreciated
