### ISSUE TITLE
Select category in mutation

### ISSUE THREAD

**Issue by nelhop** [markhuot/craftql#331]
I am trying to select (not create) a category in a mutation. 
But no matter how I formate the variable I get an error:

**Query:**
```graphql
mutation createKurs (
  $kursnummer: String
  $kursname:String
  $disziplin: [DisziplinCategoryInput]
) {
upsertKurseKurs (
  kursnummer: $kursnummer
  kursname: $kursname
  disziplin: $disziplin
  ) {
    kursnummer
    kursname
  }
}
```

**Variables:**
```json
{
  "kursnummer": "TEST123",
  "kursname": "QL Test",
  "disziplin": {
      "id": 695
    }
}
```

**Response:**
```json
{
  "errors": [
    {
      "message": "Variable \"$disziplin\" got invalid value {\"id\":695}; Expected type DisziplinCategoryInput to be an object at value.id.",
      "category": "graphql",
      "locations": [
        {
          "line": 12,
          "column": 3
        }
      ]
    }
  ]
}
```

Also tried with `"disziplin": [{
      "id": 695
    }]` but this prompts an server error.

**How has the variable to be formatted?**

_______

Craft Pro 3.4.8
CraftQL  1.3.4

**Comment by peirix** [comment]
Got the same error. The solution you tried with `[{ "id": 695 }]` is the correct way to do it, but the server error is because it's trying to fetch the category group by `id`, but the function is receiving the `uid`, so by changing `Listeners/GetCategoriesFieldSchema.php:68` from `getGroupById($groupId)` to `getGroupByUid($groupId)` it works as expected.

**Comment by nelhop** [comment]
@markhuot Is there any chance this will be fixed soon?

**Comment by nelhop** [comment]
See PR: https://github.com/markhuot/craftql/pull/336
