### ISSUE TITLE
Upserts fail without title

### ISSUE THREAD

**Issue by timkelty** [markhuot/craftql#48]
```
mutation {
  upsertOrganizations(
    phone: "555-555-5555"
  ) {
    id
  }
}
```

### Results

With `Show the Title field` checked (default) in the entry type (making title required):
```
{
  "error": "Cannot return null for non-nullable field Organizations.id."
}
```
I would expect a "Title cannot be blank." error here, not this.

------

With `Show the Title field` unchecked and a Title Format (making title not-required):

Entry created, success:

```
{
  "data": {
    "upsertOrganizations": {
      "id": 603
    }
  }
}
``` 

Likely related to #47.

**Comment by markhuot** [comment]
`dev-master` fixes this. Unfortunately I can't make `title` a required field, because if you're updating an existing entry it's perfectly fine to leave it out and retain the existing value. And until GraphQL gets InputEnum types I'm stuck with the same title field for inserts and updates.

To work around this CraftQL will now throw a `UserError` if there is no `id` or `title` set.
