### ISSUE TITLE
Fragment cache issues

### ISSUE THREAD

**Issue by keithmancuso** [markhuot/craftql#67]
I started using Vue-Apollo to with craftql and loving it so far.

Im running into issues however with one of my more complicated queries which started warning me in the console with 

```
You are using the simple (heuristic) fragment matcher, but your queries contain union or interface types.
     Apollo Client will not be able to able to accurately map fragments.To make this error go away, use the IntrospectionFragmentMatcher as described in the docs: https://www.apollographql.com/docs/react/recipes/fragment-matching.html
```

I followed its directions and created the fragments.json but now im getting errors that its missing some of the matrix definitions.  

its just running 

```

{
  __schema {
    types {
      kind
      name
      possibleTypes {
        name
      }
    }
  }
}
```

Is there a better way to get this complete list?

**Comment by markhuot** [comment]
>now im getting errors that its missing some of the matrix definitions.

Can you grab me a screen shot or copy/paste of the error you're getting? The query you pasted works okay for me and for Matrix fields I get the following with a Matrix field of `richContent` that contains an entry field and a plain text field (full of markdown).

```json
{
  "kind": "UNION",
  "name": "RichContentUnion",
  "possibleTypes": [
    {
      "name": "RichContentText"
    },
    {
      "name": "RichContentRelatedContent"
    }
  ]
},
```

**Comment by keithmancuso** [comment]
ugh so turns out im just an idiot and i was just loading the IntrospectionFragmentMatcher wrong, ugh.  Sorry to bug you with it but thanks for the quick response.

Does seem annoying to have to do this when im really just making a read only api for my data. Are you using apollo or you are you using something a little more lightweight like graphql-request or lokka?

**Comment by markhuot** [comment]
I'm using Apollo, but mostly with React. Do you have a URL for IntrospectionFragmentMatcher? I'm not sold on Union's for Matrix fields so I'd be open to altering it if it makes life in Vue easier. I'm going to reopen this while we discuss.

**Comment by keithmancuso** [comment]
yea right now it seems with unions you dont get the option of filtering the matrix fields at all which is a bummer as we often just want to grab certian blocktypes, so if theres a way to do matrix blocks as more of a sub query?  Im pretty new to graphql so not sure I really understand whats possible.

As for the Fragement matcher I dont think its a vue specific thing as I was getting a console log message from apollo-client [that linked me to a page in their docs](https://github.com/apollographql/apollo-client/blob/master/docs/source/recipes/fragment-matching.md) 

I was able to get this method to work but annoyingly i means anytime i change the schema i have to rerun this to generate the fragmentType.json

For our needs Im thinking a simplier client like [graphql-request](https://github.com/graphcool/graphql-request) will reduce some of the complexity here.

**Comment by markhuot** [comment]
Hrm, I haven't come across this, but it's probably because I've been stubborn and requesting all the page data at my top level component and just passing data down, instead of using fragments. I see, now, why the fragment matcher has trouble with unions or interfaces.

As for a fix, hrm, that's tough. Right now I, personally, like that the GraphQL schema matches `craft.entries` pretty closely. But that adds some GraphQL complexity because a `matrixField` field returns all possible block types. The intent would be to use it in this way,

```graphql
{
    entry(id:1) {
        ...on Stories {
            title
            richContent {
                ___typename
                ...on RichContentText {
                    body
                }
                ...on RichContentImage {
                    image {
                        url
                    }
                }
                ...on RichContentQuote {
                    quote
                    author
                }
            }
        }
    }
}
```

With that I usually (in my JS) loop over `richContent` and `switch` on the `__typename`. But… that only works if you're doing this all in a top-level query, I think. Long story short, I can't think of any _clean_ way to avoid the union.

--

However, to get back to one of your questions,

> with unions you don't get the option of filtering the matrix fields at all which is a bummer as we often just want to grab certian blocktypes

This is definitely possible, it's just not implemented yet. Can you filter matrix fields by block type in native Craft templates? If so, I could see something like this,

```graphql
{
  entries {
    ...on Post {
      matrixField(type:[MatrixFieldText, MatrixFieldImage]) {
        ...on MatrixFieldText {
          body
        }
        ...on MatrixFieldImage {
          image {
            url
          }
        }
      }
    }
  }
}
```

The above would filter down a matrix field to only show blocks of a certain type. You'll see that GraphQL still requires us to spread out the block types because we can't have variable field types, but it would, at least, avoid the filtering in your JS logic?

**Comment by keithmancuso** [comment]
The unions make sense to me and i was able to get them working ok with the extra small step of managing the scheme in a json file which is no problem really.

As for the matrix filtering yes you can do that kind of filtering on a matrix block in twig so I’d love to see type filtering if not other field filtering just like your example. Biggest case is like when you might want the first image from a matrix block on a number of entries for a listing page, but don’t want have to filter them down client side

**Comment by stephanedemotte** [comment]
Same here, graphql noob, vuejs and apollo client, work fine until we have to deal with matrix 

```
              work_medias {
                ... on Work_mediasImage { image { url } }
                ... on Work_mediasVideo { video }
              }
```

<img width="585" alt="screen shot 2018-04-05 at 9 45 52 pm" src="https://user-images.githubusercontent.com/2158130/38399839-c416b3ac-391a-11e8-8ab6-e554796d25b6.png">

Craft 3 is ready, craftql look pretty cool, waiting for a fix with appolo client 💃 

Thanks !

**Comment by markhuot** [comment]
I don't think I'm ready to move away from Unions for Matrix fields, yet. The alternative is just too messy and involves weird loops. That means that Apollo will require the IntrospectionFragmentMatcher to work here. There's some more detail about how to set it up here:

https://www.apollographql.com/docs/react/advanced/fragments.html#fragment-matcher

I agree that this seems overly engineered to pull Matrix fields. I'm still thinking of ways to improve this but don't have any ideas yet.

--

Unhelpful suggestion: if you avoid fragments with Matrix fields you shouldn't run in to this error. E.g.,

```graphql
{
  entries {
    ...on News {
      matrixField {
        MatrixFieldBlockOne {
          blockOneField
        }
        MatrixFieldBlockTwo {
          blockTwoField
        }
      }
    }
  }
}
```

**Comment by stephanedemotte** [comment]
Can't get your example working :/

So sorry to bother you, here my example.. , don't find a way to make it work

<img width="792" alt="screen shot 2018-04-13 at 12 58 51 pm" src="https://user-images.githubusercontent.com/2158130/38747987-adde8244-3f1a-11e8-8df1-79a056b2fcb6.png">
<img width="1172" alt="screen shot 2018-04-13 at 12 59 11 pm" src="https://user-images.githubusercontent.com/2158130/38747990-b0112300-3f1a-11e8-83a4-82c20df6bb30.png">

Thanks

**Comment by markhuot** [comment]
@stephanedemotte, try,

```graphql
{
  entries {
    ...on Works {
      work_medias {
        ...on Work_mediasImage {
          imageImage
        }
      }
    }
  }
}
```

Note, the difference here, for the block _type_ you need to use a GraphQL type, which means using `...on` at the beginning.

**Comment by stephanedemotte** [comment]
![screen shot 2018-04-17 at 9 51 45 am](https://user-images.githubusercontent.com/2158130/38873953-f6d9cde8-4224-11e8-9bba-2e315838dff3.png)

Same error

**Comment by markhuot** [comment]
So, this is actually a different issue. The issue now is that `imageImage` is not the correct field name. Within your `image` block type you have an Assets field, I assume. You should replace `imageImage` with whatever the handle of that assets field is, maybe just `image`?

**Comment by stephanedemotte** [comment]
Ah ok, so now i have "again" the `WARNING: heuristic fragment matching going on!`

So we have no choice, if we want to use Craftql with Vue and Apollo, we must use `IntrospectionFragmentMatcher`

It's clear now, maybe a note in the doc for other vue/appollo users could be cool :)

Thanks again !

**Comment by markhuot** [comment]
That makes a lot of sense @stephanedemotte. I'll get the docs updated. I also an example of it running when Webpack compiles that may be of use to some people.

**Comment by markhuot** [comment]
This is actually a "feature, not a bug."

The reason for this is that Apollo has the ability to cache everything. Normally it can do this because it can cache the `entries` knowing it will be of type `EntryInterface`. It can cache `contentPhoto` because it knows it will be of type `DefaultAssetVolume` (or something). Apollo can't cache `resource` because it doesn't know what it will find within that field. You can work around this by telling Apollo about your schema. The React docs do a pretty decent job describing it,

https://www.apollographql.com/docs/react/advanced/fragments.html#fragment-matcher

You can find some JS on that linked page that will save out a `fragmentTypes.json` file. That should silence the warning you're getting and allow Apollo to use its cache fully.

I'm going to leave this ticket open because the issue has come up enough that I'd like to build in a Craft CLI tool to help here.

**Comment by markhuot** [comment]
> I guess my question now, is that why does this work inside of the graphQL debugger, and not within apollo client?

The GraphiQL interface does not provide any level of caching. Because of this you can mix and match fragments as much as you'd like without running in to this sort of issue. In fact the GraphiQL UI uses the browser's native `fetch` implementation (where available) to make a simple POST with no added bells and whistles. You can see that here,

https://github.com/markhuot/craftql/blob/master/src/templates/graphiql.html#L143-L164

As for why it "doesn't work" in Apollo it's because Apollo would like you to do some additional work to teach the client of the schema (and possible fragment types). Their docs have [the following](https://www.apollographql.com/docs/react/advanced/fragments.html#fragment-matcher),

> ```
>query {
>  all_people {
>    ... on Character {
>      name
>    }
>    ... on Jedi {
>      side
>    }
>    ... on Droid {
>      model
>    }
>  }
>}
>```
>
>In the query above, all_people returns a result of type Character[]. Both Jedi and Droid are possible concrete types of Character, but on the client there is no way to know that without having some information about the schema. By default, Apollo Client’s cache will use a heuristic fragment matcher, which assumes that a fragment matched if the result included all the fields in its selection set, and didn’t match when any field was missing. This works in most cases, but it also means that Apollo Client cannot check the server response for you, and it cannot tell you when you’re manually writing an invalid data into the store using update, updateQuery, writeQuery, etc.

What that's saying is that if your query returned `Jedi#1` and `Droid#1` all Apollo would see is,

```
{
  "all_people": [
    {"id": 1, "name": "Obi-Wan Kenobi"},
    {"id": 1, "name": "R2-D2"}
  ]
}
```

With that there's no way to Apollo to cache the "Characters" because there's nothing unique about each. If you pass a `IntrospectionFragmentMatcher` in to Apollo's `InMemoryCache` you can teach it the difference between Jedi and Droids so it doesn't have that problem.

----

It's worth noting all that "ideal use case" stuff above is all well and good but doesn't help any of you today. I'm working on a way to make this less painful to get up and running. Matrix blocks are one of my favorite parts of Craft but if they're going to be a pain to use in CraftQL then that doesn't do us any good. I'll keep this ticket open and update you all as soon as I'm able.

**Comment by thatONEjustin** [comment]
I actually got around the issue by writing out my queries with implicit typing:

```
pdfs: entries(section: [resources], type:ResourcesResourcePdf) {
				  ... on ResourcesResourcePdf {
					title
					category {
						id
					}
					contentPhoto {
					  regular: url(crop: {height: 150, quality: 85, format: png})
					  retina: url(crop: {height: 300, quality: 100, format: png})
					}
					pdfDownload {
					  url
					}
				  }
				}
				links: entries(section: [resources], type:ResourcesResourceLink) {
				  ... on ResourcesResourceLink {
					title
					category {
						id
					}
					contentPhoto {
					  regular: url(crop: {height: 150, quality: 85, format: png})
					  retina: url(crop: {height: 300, quality: 100, format: png})
					}
					external_link
				  }
				}
			  }
```

 a bit hacky but I needed to manipulate the data after receiving so this is a good bandaid for now. Thanks for the fast responses and patience!

**Comment by markhuot** [comment]
I just added a `./craft` CLI command called `fetch-fragment-types`. It is called like so,

```bash
$ ./craft craftql/tools/fetch-fragment-types
```

That will echo out a JSON blob of possible fragment types. If you save that out to a `.json` and pass it in to your Apollo `InMemoryCache` it should silence the warnings you're seeing. Such as,

```bash
$ ./craft craftql/tools/fetch-fragment-types > fragmentTypes.json
```

Then in your JS, wherever you initialize Apollo,

```js
const IntrospectionFragmentMatcher = require('apollo-cache-inmemory').IntrospectionFragmentMatcher
const introspectionQueryResultData = require('./fragmentTypes.json') // get the JSON CraftQL just saved out

const fragmentMatcher = new IntrospectionFragmentMatcher({ // create a new fragment matcher
    introspectionQueryResultData
})

const cache = new InMemoryCache({ fragmentMatcher }) // pass the fragment matcher in to your cache
```

----

Note: this is all on `dev-master`

**Comment by markhuot** [comment]
FYI, @keithmancuso, you had asked if you could filter matrix fields by type, well you now can on `dev-master` E.g.,

```graphql
{
  entries {
    ...on EntryType {
      matrixField(type:"typeHandle", limit:123) {
        ...
      }
    }
  }
}
```

**Comment by markhuot** [comment]
[1.1.0](https://github.com/markhuot/craftql/blob/master/CHANGELOG.md#110---2018-06-27) was released on 2018-06-27 and includes the fragment JSON generator.
