### ISSUE TITLE
Javascript Error 404 Not Found

### ISSUE THREAD

**Issue by theskyfloor** [markhuot/craftql#84]
CraftQL can't connect to the api end point - I am testing on a live URL (on my staging Craft 3 install, I am just on a public URL so I dont have to mess with my private staging URL)... when I visit the API end point directly it says `Template not found: api`. Any ideas? I would love to test this plug-in out!

**Comment by markhuot** [comment]
It almost sounds as if CraftQL isn't installed… If you navigate to `/admin/settings` do you see the QL logo in the bottom "Plugins" section?

![screen shot 2018-04-09 at 12 44 05 pm](https://user-images.githubusercontent.com/48975/38510671-b57173ec-3bf3-11e8-99a7-d0425841dc97.png)

Also, when you navigate in to the CraftQL settings is the URI set to `api`?

![screen shot 2018-04-09 at 12 44 24 pm](https://user-images.githubusercontent.com/48975/38510699-c73c65be-3bf3-11e8-93a0-e789f6b0262a.png)

If both those things are true then this is a new bug. Can you let me know the version of Craft and the version of CraftQL you're running?

**Comment by theskyfloor** [comment]
Yes and yes... hmm I am on an old version 3.0.0.2 and it isn't updating. I might nuke this install and start over. Unless you want to look at it? This is my oldest Craft 3 beta install and it looks like it might have developed some corruption over time.

**Comment by markhuot** [comment]
Nah, feel free to nuke it. This is the only report like this so I'm not inclined to spend too much time on it if a fresh install fixes it all up.

**Comment by theskyfloor** [comment]
Fresh install fixed it! Thanks!

**Comment by swthate** [comment]
I am having this same issue also. I managed to get the default curl command to return HelloWorld. So that part is working, and CraftQL is definitely installed and functioning.

Craft: 3.0.26.1
CraftQL: 1.1.0

Here is my error object from the console:
```json
config:
    adapter: ƒ (e)
    baseURL: "http://craft.test/api"
    data: undefined
    headers: {Accept: "application/json, text/plain, */*", Authorization: "Bearer Wa2c1n_5mB5zndY7ttcYDzybaFhkfLivQS0TmLy0bRjY3ybdMzKvs56x-GJ3FmSU", X-Requested-With: "XMLHttpRequest"}
    maxContentLength: -1
    method: "get"
    query: "↵    {↵        entries(section:[posts]) {↵            title↵            postDate↵        }↵    }↵"
    timeout: 0
    transformRequest: {0: ƒ}
    transformResponse: {0: ƒ}
    url: "http://craft.test/api"
    validateStatus: ƒ (e)
    xsrfCookieName: "XSRF-TOKEN"
    xsrfHeaderName: "X-XSRF-TOKEN"
    __proto__: Object
data:
    error: "Template not found: api"
    __proto__: Object
headers:
    cache-control: "no-store, no-cache, must-revalidate"
    connection: "Keep-Alive"
    content-length: "35"
    content-type: "application/json; charset=UTF-8"
    date: "Tue, 09 Oct 2018 15:21:54 GMT"
    expires: "Thu, 19 Nov 1981 08:52:00 GMT"
    keep-alive: "timeout=5, max=98"
    pragma: "no-cache"
    server: "Apache"
    x-powered-by: "Craft CMS"
    __proto__: Object
request: XMLHttpRequest
    onabort: null
    onerror: ƒ ()
    onload: null
    onloadend: null
    onloadstart: null
    onprogress: null
    onreadystatechange: ƒ ()
    ontimeout: ƒ ()
    readyState: 4
    response: "{"error":"Template not found: api"}"
    responseText: "{"error":"Template not found: api"}"
    responseType: ""
    responseURL: "http://craft.test/api"
    responseXML: null
    status: 404
    statusText: "Not Found"
    timeout: 0
    upload: XMLHttpRequestUpload {onloadstart: null, onprogress: null, onabort: null, onerror: null, onload: null, …}
    withCredentials: false
    __proto__: XMLHttpRequest
status: 404
statusText: "Not Found"
__proto__: Object
```

Here is my javascript in case that is causing any issue:
```javascript
const token = 'Wa2c1n_5mB5zndY7ttcYDzybaFhkfLivQS0TmLy0bRjY3ybdMzKvs56x-GJ3FmSU';
const url = 'http://craft.test/api';
const query = `
    {
        entries(section:[posts]) {
            title
            postDate
        }
    }
`;

const axiosCraftQL = axios.create({
    baseURL: url,
    headers: {
        'Authorization': `Bearer ${token}`,
        'X-Requested-With': 'XMLHttpRequest'
    }
});

new Vue({
    el: '#app',
    delimiters: [ '${', '}' ],
    data: {
        entries: {}
    },
    mounted() {
        axiosCraftQL
            .get(url, { query: query })
            .then(response => {
                console.log(response)
            })
            .catch(error => {
                console.log(error.response)
            });
    }
});
```

I was getting this same `template not found: api` error on my original development site. This is a new install I am trying on and I'm getting the same error.

**Comment by markhuot** [comment]
Can you confirm that the CraftQL settings have the URI set to `api`? This also feels like Craft can't find the plugin for some reason. Best bet is probably to uninstall and re-install the plugin.

**Comment by swthate** [comment]
@markhuot this is just bizarre.

I did another Craft install from scratch. The last one I did wasn't completely from scratch as it turns out, it was using a database backup from a previous test. Anyway. New Craft install, new CraftQL install. Got the new token set up and made sure the right section was enabled inside there. But I'm still getting `error: "Template not found: api"`

I'm not sure what could be causing this yet. So here are some version numbers of what I'm running that may or may not prove useful:

```
Craft     3.0.27.1
CraftQL   1.1.0 (no other plugins installed)
MAMP Pro  5.1.1
MySQL     5.7.23
PHP       7.2.8
```

**Comment by narration-sd** [comment]
@swthate  looking over your code, I suspect the problem is  that you're asking axios to do a GET instead of a POST. CraftQL defaults to allowing only POST -- you can look into config to arrange else, but in my opinion this is pretty wise for several reasons.

When you attempt a get, the internal routing the plugin arranges isn't present for that, so Craft itself doesn't know what to do with it. Hence you get the 404. 

A token problem would have given you a different error, that you were unauthorized, and it would have come from CraftQL itself. Bon appetit...

**Comment by markhuot** [comment]
Thanks @narration-sd, I was just thinking the same thing.

@swthate in your script above you need `axiosCraftQL.post` instead of `.get`.
