### ISSUE TITLE
Not able to query image transform attributes

### ISSUE THREAD

**Issue by exophunk** [markhuot/craftql#94]
It would be nice if you could not only query the url of an image transform, but also other attributes like width, height etc.

```gql
width(transform: productDesktop)
```

Example query: 

```gql
  entries(section: [products], limit: 15) {
    ... on Products {
      imageField {
        widthDesktop: width(transform: productDesktop), // allow this
        desktop: url(transform: productDesktop),
      }
    }
  }
```

Something similiar to the twig method `{{ asset.getWidth(thumb) }}` (According to [Craft 3 Docs](https://docs.craftcms.com/v3/image-transforms.html#applying-cp-defined-transforms-to-images))

This is needed, if you want to e.g. create responsive images and need to know the width and height of the different transforms. Else, you need to store a copy of the transforms somewhere on the client or fetch them elsewhere.

**Comment by exophunk** [comment]
Yes, I think both approaches would be okay, as long as its possible somehow to fetch image transform attributes. I think I would prefer your variant, as it feels more graphql like...

For now, there is no way to retrieve data about the image and I have to keep a copy of image transform settings clientside.

**Comment by markhuot** [comment]
This is now implemented on `dev-master`. I went the "Craft way" instead of the GraphQL way, though, because I'm really trying to keep feature parity with `craft.entries` and what developers are used to in the template. Because of that you have to pass the transform to the `width` and `height` fields, explicitly. E.g.,

```graphql
{
  entry {
    ...on EntryType {
      imageField {
        url(transform: transformHandle)
        width(transform: transformHandle)
        height(transform: transformHandle)
      }
    }
  }
}
```

----

Note, at some point, later on, I may revisit and add the transform to the field _in addition_ to this approach.

**Comment by markhuot** [comment]
[1.1.0](https://github.com/markhuot/craftql/blob/master/CHANGELOG.md#110---2018-06-27) was released on 2018-06-27 and includes this fix.
